name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: run protolint
        uses: plexsystems/protolint-action@v0.7.0

  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Install Protoc
        uses: arduino/setup-protoc@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'
      - name: Install protoc-gen-go
        run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - name: Install protoc-gen-go-vtproto
        run: go install github.com/planetscale/vtprotobuf/cmd/protoc-gen-go-vtproto@latest

      - name: generate language files
        run: make build clean
        env:
          GOPATH: /root/go
